Added console input History, and trap Error in Try-Catch
fuel/oil pull request #271
Opened 2020-11-02 02:08 UTC by mingfudesign

Added $history to track latest 99 valid inputs
Added commands for showing console inputs
Added pre-amble at Console start to list available commands
Try-Catch traps Errors to prevent Console from exiting automatically

2020-11-02 14:54 UTC, WanWizard requested changes
Thanks for your contribution, much appreciated!

Could you please address the comments?

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
>   */
Please undo the changes in the header (no tabs).

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +	private $history = [];
Class variables should be defined at the top, before the constructor, not in the middle of the code.
Also, never use "private", use "protected". All Fuel classes should be fully extendable.

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +	private function push_history($line)
protected instead of private.

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +	private function pop_history()
protected instead of private.

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +	private function show_history()
protected instead of private.

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +		\Cli::write(['', 'Commands', ':q | quit - exit the console', ':h | history - show transcript', '']);
No short array notation please, Fuel still requires PHP 5.6 compatibility.

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
>  	private function main()
Please while you're at it, please change this to protected too...

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +			if ($__line == ':q' || $__line == 'quit')
Please use "or" instead of "||" ( coding standards )

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +			elseif ($__line == ':h' || $__line == 'history')
Please use "or" instead of "||" ( coding standards )

2020-11-02 14:54 UTC, WanWizard commented on classes/console.php
> +			catch(\Exception|\Error $e)
Catching multiple exceptions isnt supported in PHP < 7.1, so please split this.

2020-11-03 12:16 UTC, mingfudesign commented
I think, with the latest changes, all of the comments have been addressed. Please check.

2020-11-06 17:38 UTC, WanWizard commented
Looks fine, thanks !

2020-11-06 17:38 UTC, merged